### PR TITLE
NeuroHub users can reset their pw.

### LINKED ISSUE #956: NeuroHub Alpha user feedback - technical issue -  login sequence issue between NeuroHub and CBRAIN
Reference survey containing raw data feedback in spreadsheet format:
https://docs.google.com/spreadsheets/d/1yt3iKKlMoRUgZl9E_fomAVgj38CgvJ2K3AKIeB3tMDQ/edit#gid=675520657

Feedback from Lex Hutton regarding the following technical experience issues (to split as needed into separate items):

- Logging into NH redirected me to CBRAIN instead of NH. 
- Re-logging brought up an error ("a message was sent to admins").
- Further logins sent me to NH.

### PR DESCRIPTION
**Pull request by prioux**
New intercept for accounts with forced
reset_password. Also users can change their
password, while we're at it.

This will fix #956 , #957 e) and #991

### CODE REVIEW

**Comment by prioux** [comment]
@candicecz I'd like you to have a look at the link I added in the MyAccount page; I wanted a link to the change password page, and I figured putting it just besides the edit button was fine. I also used the same little icon. But maybe you have a better idea?

**Comment by prioux** [comment]
@natacha-beck Candice already approved (based on a quick phone conversation this morning, but she should click the approve button too) and if we decide to change the icon for the 'change password' button, we can do that later. No need to edit this PR for that.

I want the PR merged ASAP, so I'm just waiting for @MontrealSergiy 's review.

**Comment by candicecz** [comment]
I approved though we should also in some way circumvent the user from submitting empty fields and then receiving a "Password change successful" banner at the top. I talked about this with Pierre this morning.

**Comment by prioux** [comment]
@candicecz I forgot about that bug report. I'll handle it now.

**Comment by prioux** [comment]
Well, I got approval from two reviewers out of three (Natacha, Candice vs Sergiy), so I will merge this now.

**Pull request merged**
