### PR TITLE
Swagger format

### PR DESCRIPTION
**Pull request by MontrealSergiy**
swagger improvements

### CODE REVIEW

**Comment by prioux** [comment]
Please move this PR to the dev branch, it's properly based on dev but by merging into master we'd get commits that do not belong there yet (as can be seen in https://github.com/aces/cbrain/network )

**Comment by prioux** [comment]
All is good except one thing: I am not sure about that `enum: ["true", "false"]` is actually ok in all the cases of the spec. We have not been consistent in our handling of such attributes, and I fear sometimes we have `"0", "1"` or `true, false` (which is different from `"true", "false"`)... these need to be checked.

**Comment by prioux** [comment]
I suggest looking at the CURL outputs. Just running all the tests with `-v5` should provide all the information.

**Comment by MontrealSergiy** [comment]
Looks like it returns actual boolean, and swagger 2 does not seem support oneOf ( several types) .

Loris actually uses an empty string for account_locked, so switching to type: boolean would make his client invalid

**Comment by prioux** [comment]
The swagger spec is now in files with "5.1.1", and also I am still not convinced the proper values are specified for the boolean returns. We need to be consistent, including modifying the controllers as necessary. The JSON output shoudl have `true` and `false` everywhere.

**Comment by shots47s** [comment]
Is this pull request still necessary?

**Comment by prioux** [comment]
@shots47s Well I wanted Sergiy to perform an audit of all the true/false/"true"/"false" values of our JSON outputs, and fix the controllers and the swagger spec as necessary. The PR itself is useless because it modifies swaggers specification files that are not supposed to be touched (we normally create new ones as we improve them).

**Comment by prioux** [comment]
So I'll reject it and create an issue.

**Pull request closed without merging**
