### PR TITLE
Misc small changes.

### PR DESCRIPTION
**Pull request by prioux**
* Dearchiving a task updates updated_at timestamp
* Added DB consistency rules to SyncStatus model
* Removed 'Mozilla Persona' in login page HTML

### CODE REVIEW

**Comment by glatard** [comment]
Just curious: why is Mozilla Persona removed from login page?

**Comment by driusan** [comment]
Mozilla killed Persona. The service doesn't exist anymore.

**Comment by prioux** [comment]
@glatard @driusan Yes, Persona is dying.

But I removed Persona log in for another reason too. I've had several instances of people trying to connect to CBRAIN using persona, thinking they could use the service even though they didn't have an account. They thought Persona was a way to not only log in, but also to sign in for the service.

For the moment I only removed the Persona arrow in the login page and I've left the Persona code in the session controller, but I'll clean this up shortly too.

**Comment by glatard** [comment]
Persona or not persona, maybe it would be useful to have a link to sign in to CBRAIN (i.e. create an account) instead of keeping it private. Removing a login option is not going to make account creation clearer...

**Comment by glatard** [comment]
And yes, Persona will be decommissioned, in November 2016 (see #292). That should have left us some time to talk about possible replacements.

**Comment by prioux** [comment]
Yes, we have an issue (was it in Redmine? must be on GitHub now) about having a configuration option in CBRAIN so that the admin can provide a link to a signup page. Then the link would appear within the login page. Or we could build a signup service within CBRAIN too.

**Pull request merged**
