### PR TITLE
Switching project clears the persistent list of userfiles.

### PR DESCRIPTION
**Pull request by prioux**
Please test this.

I also highlighted the number of selected files in red in the interface.

### CODE REVIEW

**Comment by prioux** [comment]
This will fix #671 and #685

**Comment by shots47s** [comment]
Looks good to me.

**Comment by prioux** [comment]
I'm going to rebase this on dev.

**Comment by prioux** [comment]
OK I rebased this on dev.

**Comment by natacha-beck** [comment]
Seems buggy on my side. For my test: 

I was on `All` I selected 2 files. 

all

Then I switched to my project `a`, and the 2 same files were still selected: 

a

And I am sure that I have the latest commit of this PR.

**Comment by prioux** [comment]
@natacha-beck Your number is red so it means you do have the proper code. It's possible something doesn't work on Chrome; the list clearing code is tricky with side effects and dependencies on timing. One thing you can try is to make sure that the .js file is not cached by the browser (on my mac, command-shift-r was needed for me to test properly). I'll test further on Chrome tomorrow. Thanks for the feedback!

**Comment by prioux** [comment]
I have just tested on Chrome and got your buggy behavior, until I hit command-shift-R and then it worked properly.

**Comment by natacha-beck** [comment]
It was due to some caching. I was able to test it properly today.

**Pull request merged**
