### PR TITLE
Portal and Bourreau communicate over tunnelled UNIX domain sockets

### PR DESCRIPTION
**Pull request by prioux**
In the traditional communication mechanism that we've been using for 10 years, the Portal and the Bourreau communicate with each other using network sockets tunneled by SSH.

Conceptually:

```shell
# Portal made ActiveResource calls to 3901 and bourreau listened on 2345
# Portal reverse forwarded the DB on 7890
ssh -L 3901:localhost:2345 -R 7890:localhost:3306 bourreauhost
```

At the time the CBRAIN project started, SSH did not have the ability to tunnel to UNIX domain sockets on its listener or emitter side. Now that this is possible, this PR makes the master connection establish one listener socket on the bourreau side (for the db) and forwards portal connection to another socket that the bourreau listens to (for the ActiveResource calls)

Conceptually:

```shell
# Here, bourreau.sock is a socket on the bourreau side created by the bourreau when it boots
# and db.sock is a listener socket on the bourreau side that SSH itself sets up.
ssh -L localhost:3901:/path/to/bourreau.sock -R /path/to/db.sock:localhost:3306 bourreauhost
```

### CODE REVIEW

**Comment by prioux** [comment]
To test this: make sure your test bourreaux are off. Pull the ocde on both sides. Start a bourreau. Perform normal operations.

**Comment by prioux** [comment]
The latest commit https://github.com/aces/cbrain/pull/1229/commits/82579a68d2919f9748b110b9bb9adbaa56709d13 implements #1231

**Comment by natacha-beck** [comment]
Works fine on my dev env.

**Comment by prioux** [comment]
I looked up the OpenSSH release logs online, and sure enough, like I said in my description, the ability to tunnel with UNIX domain sockets was implemented in 2014, several years after I created my initial SshMaster library.

**Pull request merged**
