### PR TITLE
[FIX] issue #931: Add Public Project to CBRAIN

### PR DESCRIPTION
**Pull request by candicecz**
[[ADD] Public project to CBRAIN project index #931](https://github.com/aces/cbrain/issues/931)

### CODE REVIEW

**Comment by candicecz** [comment]
Not ready yet. Making tasks 'public' still needs to be done.

**Comment by prioux** [comment]
This PR now has conflicts.

Also, what is happening with it? What is the issue about exactly? Maybe it's better to restart the fix from scratch?

**Comment by candicecz** [comment]
This PR allows viewing "public" files in CBRAIN, however "public" tasks are not viewable. The issue is with how data providers work currently in CBRAIN. Some adjustments would need to be made to allow public tasks to show for everyone. Now that the merge with Neurohub and CBRAIN is complete it might be better to close this and just start from scratch.

**Comment by prioux** [comment]
@candicecz If you prefer to close the PR and start again, go ahead.

**Pull request closed without merging**
