### PR TITLE
Added info viewer for Singularity image files.

### PR DESCRIPTION
**Pull request by prioux**

### CODE REVIEW

**Comment by MontrealSergiy** [comment]
Does not handle well unicode rendering. Rendering of metadata could be improved 
image

**Comment by MontrealSergiy** [comment]
Also are headers meaningful for the BEst tool? (available in CBrain)

**Comment by prioux** [comment]
Weird. Why are there ANSI sequences in the output?

Also, how come your output of the inspect seem to be json? I get plain text like:

```
==labels==
org.label-schema.schema-version: 1.0
org.label-schema.usage: /.singularity.d/runscript.help
org.label-schema.usage.singularity.deffile.bootstrap: library
org.label-schema.usage.singularity.deffile.from: centos:7
org.label-schema.usage.singularity.deffile.mirrorurl: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/x86_64/
Author: pierre.rioux@mcgill.ca
Version: v1.0.1
org.label-schema.build-date: Friday_22_November_2019_14:55:50_EST
org.label-schema.usage.singularity.deffile.osversion: 7
org.label-schema.usage.singularity.runscript.help: /.singularity.d/runscript.help
org.label-schema.usage.singularity.deffile.include: yum
org.label-schema.usage.singularity.version: 3.4.1-1.2.el7
```

**Comment by MontrealSergiy** [comment]
singularity version issue?

**Comment by MontrealSergiy** [comment]
OK. May be it's my machine issue - did not update singularity (no sudo here)

**Comment by prioux** [comment]
Please provide me with the command-line outputs of these commands:

```
singularity inspect imgfile
singularity sif header imgfile
singularity sif list imgfile
singularity sif info 1 imgfile
singulariry sif info 2 imgfile
```

Quote each one separately please.

**Comment by MontrealSergiy** [comment]
```sboroday@ace-ws-50:/data1/users/sboroday$ singularity --version
2.5.2-dist
sboroday@ace-ws-50:/data1/users/sboroday$ singularity inspect $img
{
    "maintainer": "Oba\u00ef Bin Ka'b Ali <ali.obai.b.k@gmail.com>"
}
sboroday@ace-ws-50:/data1/users/sboroday$ singularity sif header $img
ERROR: Unknown command 'sif'
sboroday@ace-ws-50:/data1/users/sboroday$ singularity sif list $img
ERROR: Unknown command 'sif'
sboroday@ace-ws-50:/data1/users/sboroday$ singularity sif info 1 $img
ERROR: Unknown command 'sif'
sboroday@ace-ws-50:/data1/users/sboroday$ singulariry sif info 2 $img
No command 'singulariry' found, did you mean:
 Command 'singularity' from package 'singularity' (universe)
singulariry: command not found
sboroday@ace-ws-50:/data1/users/sboroday$ 
```

**Comment by prioux** [comment]
Oh well, we'll simply not support older singularity

**Comment by MontrealSergiy** [comment]
and older singularity images with new singularity

```singularity sif header spark.simg
Error for command "header": invalid SIF file: Magic |sqs���| want |SIF_MAGIC|

Usage:
  singularity [global options...] sif header <containerfile>
```

**Comment by MontrealSergiy** [comment]
Not big deal but ideally the headers should be disabled, supressed for older formats .(s)img .

**Comment by prioux** [comment]
I'll leave it as-is. After much work I configured a remote portal that allowed me to test all sort of other situations, and it's all good enough.

**Comment by MontrealSergiy** [comment]
Ok, btw *.sif is autorecognized now

**Pull request merged**
