### PR TITLE
First LORIS hooks.

### PR DESCRIPTION
**Pull request by prioux**
Controller: NhLorisHooksController
Actions:    :file_list_maker

Given a JSON in a POST such as:

{
   "source_basenames": ["14074_0-Mammouth-S-49312-1", "ada.txt" ],
   "source_dp_id": 8,

   "result_dp_id": 8,
   "result_filename": "blah-lh",
   "result_group_id": 2
}

will find the sources (and make sure only one file match each
basename) and create a result CbrainFileList out of it.

### CODE REVIEW

**Comment by xlecours** [comment]
I am ok with a `HTTP/1.1 200 OK` with a body but a a 201 with Location header would have been fine as well.

**Comment by prioux** [comment]
@xlecours You do get a 201 status (see the line :status => :created) but I forgot to add the Location header. I will add it.

**Comment by prioux** [comment]
@xlecours Added.

**Comment by prioux** [comment]
Right now the response looks like this (output of `curl -D -`)

```
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: http://localhost:3000/userfiles/14363
Content-Type: application/json; charset=utf-8
ETag: W/"d82adaea8f479eaacc6c63973c319186"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 690fde99-1676-4996-ba95-cd21e9325923
X-Runtime: 0.511555
Transfer-Encoding: chunked

{"message":"CbrainFileList file created","userfile_id":14363,"userfile_name":"test-nh.2020-08-13-14:20:43.csv","group_id":386,"group_name":"test r5 2","data_provider_id":8,"data_provider_name":"SmartBianca","cbrain_url":"http://localhost:3000/userfiles/14363"}
```

**Comment by natacha-beck** [comment]
Tested and works perfectly well on my side.

**Comment by prioux** [comment]
Cool. Thanks Natacha.

**Comment by prioux** [comment]
Natacha and Xavier looked at it, so I will merge too.

**Pull request merged**
