### PR TITLE
Improve long select-box with chosen

### PR DESCRIPTION
**Pull request by natacha-beck**
This PR is related to issues #663 and #217

### CODE REVIEW

**Comment by prioux** [comment]
I would prefer it if the the stylesheets, javascript and images were configured under the Rails assets management pipeline (app/assets/*) instead of the public directory.

**Comment by prioux** [comment]
I'm starting to think maybe we should do this to ALL select inputs. E.g. here's the task control section, with two Chosen select and two normal ones:

Screen Shot 2019-12-11 at 14 24 55

**Comment by natacha-beck** [comment]
> I'm starting to think maybe we should do this to ALL select inputs. E.g. here's the task control section, with two Chosen select and two normal ones:
> 
> Screen Shot 2019-12-11 at 14 24 55

Agree.

**Comment by prioux** [comment]
The chosen library seems to disable the actual `select` element and builds its own set of divs and spans for the new selection box. This means we lose all the functionaly of auto-refresh (on change triggers), e.g. when selection a new tool version in the task params

make sure all select box affected work properly and send their result properly.

**Comment by prioux** [comment]
Is this all ready now?

**Pull request merged**
