### PR TITLE
A user creating a license automatically signs it. Fixes #960

### LINKED ISSUE #960: NeuroHub Alpha user feedback - technical issue - license and project creation
Received via direct email message sent to Diana:

a) Licence: Easy. If it’s ‘mandatory’ to sign it (as the creator of the project) should it pop-up when creating a project … asking you to create a licence and sign it?

### PR DESCRIPTION
**Pull request by prioux**
@MontrealSergiy Since you're the one who created the custom license module, I'm asking you in particular to review the code.

### CODE REVIEW

**Comment by MontrealSergiy** [comment]
image

**Comment by MontrealSergiy** [comment]
image

On the license creation page user is told that he will have to sign the license, which never happens.

**Comment by MontrealSergiy** [comment]
More, if license creator latter opens a license, on the next screen user is told that he signed all the licenses and this one in particular, which he never did.

**Comment by prioux** [comment]
I'll adjust the wording. Anything else about the functionality? Bugs? Security issues?

**Comment by MontrealSergiy** [comment]
Functionally it seems works as intended, found no bugs. I would also adjust the verbiage of the log messages when the license is 'autosigned'.

**Comment by MontrealSergiy** [comment]
also the snapshot of another message that needs adjustment

image

**Comment by prioux** [comment]
@MontrealSergiy Check the new messages. See commit https://github.com/aces/cbrain/pull/981/commits/d7eeb0757589695a8f64bd5b822fda329a343022 . Thanks.

**Comment by MontrealSergiy** [comment]
Wording is better. There is a typo in implic**i**tely. I would drop word implicitely completely from "You, as the author, will be be considered as having signed it implicitely."  The less Latin the easier to understand and less chances for typos. I  suggest drop "implicitly" from the sentence.  And rename button to "Add and sign the license", so signing is no longer implicit? 

Optional alternative wording "Note, we assume that by clicking create button adding this license you sign it and accept all the term and condition yourselves. "

**Comment by prioux** [comment]
I'll fix the typo in a future commit

**Comment by prioux** [comment]
Note: checks all succeeded, I canceled the last one that was triggered by a commit where I was fixing a typo in the text.

**Pull request merged**
