### PR TITLE
update link to testers survey resolves #1022

### LINKED ISSUE #1022: update to survey link in the NeuroHub Portal to reference Beta questionnaire
On the NeuroHub portal dashboard page there is on the bottom left a link to the user survey form.  That link is presently pointing to the NeuroHub Alpha User Testing Survey.

See the attached image.

The survey has been updated slightly to reflect the Beta testing environment.  As such the link on the page needs to be updated, since a reminder will be today going out to users asking them to provide their feedback.

Please update the survey link to point to the NEW location.

Old Survey Link:
https://docs.google.com/forms/d/e/1FAIpQLSepzm7l-OwvU_XN-b8ZRZF5aDJgi3QXGq_AqM0Zj9x-Asiw4w/viewform
New Survey Link:
https://docs.google.com/forms/d/e/1FAIpQLSfQnYwSUgzj6VMXEUMFEpsFZC0A9lwJVSc-Vbvpy3drjmebkQ/viewform

On https://portal.neurohub.ca/neurohub:
Screen Shot 2020-09-23 at 1 43 54 PM

### PR DESCRIPTION
**Pull request by MontrealSergiy**

### CODE REVIEW

**Comment by prioux** [comment]
Bryan wanted 'Dear users' too. Check the discussion in the issue.

**Comment by MontrealSergiy** [comment]
' Dear users'  are added

**Comment by prioux** [comment]
Can you please review your diffs *before* you even commit and push?

The welcome text now says `NeuroHub is NeuroHub is building upon and continuing advance` !

**Comment by MontrealSergiy** [comment]
repetition removed

**Pull request merged**
