### PR TITLE
boutiques parameter line breaks

### PR DESCRIPTION
**Pull request by MontrealSergiy**
This is to allow boutiques parameters descriptions include line breaks (Darius request).

I was not able to reopen previous https://github.com/aces/cbrain/pull/1151, so I opened this new pr

see 1151 for previous discussions. This is lightweight version compared to the previous, only tackles the params in task view but does not need any imports. 

PS. Personally, I think displaying parameters in verbatim mode (`<pre>`) would look nicer, though I know that not everybody likes fixed fonts. Perhaps, a subset of html/bbcode/markdown may allow for more eye candy.

### CODE REVIEW

**Comment by prioux** [comment]
What about doing the same thing for the group description too?

**Review by prioux — CHANGES_REQUESTED** [review]
Do the same for groups

**Comment by MontrealSergiy** [comment]
Doing 'same' for group description requires import which you do not like or some workaround. The request was just for parameter descriptors, group descriptors are usually short and less structured.  May be let's concentrate then on parameter descriptors?

**Comment by prioux** [comment]
Wouldn't that work?

```diff
diff --git a/BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb b/BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
index 742311b7f..67b3f3548 100644
--- a/BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
+++ b/BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
@@ -450,7 +450,9 @@
         <%= name %> <%% groupCheckbox.('<%= id %>',<%= defaultChecked %>) %>
       </h3>
       <h5 style="font-size : 9.5pt; font-weight: normal; padding-top: 2px;" class="grp-desc">
-        <%= groupDescription %>
+        <% (groupDescription.presence || "").split("\n").each do |line| %>
+          <%= line %><br>
+        <% end %>
       </h5>
     </div><%%= "<br>".html_safe %>
     <%# Write group parameters (required ones first) %>
```

**Comment by MontrealSergiy** [comment]
Yup sure, I did not suggested it due to not using escape method. Note this is adding an extra unneeded line break. E.g. if even if there is no '\n' one line break is added. To avoid extra linebreak, something like

`       <h5 style="font-size : 9.5pt; font-weight: normal; padding-top: 2px;" class="grp-desc">
-         <%= groupDescription %>
+        <%= lines = (groupDescription.presence || "").split("\n") # map linebreaks into html
+        <% lines.shift       
+        <% lines.each do |line| %>
+           <br><%= line %>
+        <% end %>
       </h5>`

well can added whichever difference is marginal

**Comment by prioux** [comment]
We're in the context of an `<H5>` anyway, so '<P>' are probably not allowed or recommended.

If putting the `<BR>` tag before the lines improves the esthetics, do it that way.

**Comment by MontrealSergiy** [comment]
I do not see any noticeable change in visuals (Chrome), my suggestion was just to avoid unnecessary tags. Accepted your version

**Pull request merged**
