### PR TITLE
remove code repetition (DRY)

### PR DESCRIPTION
**Pull request by ArminTaheri**
Just wondering why code was being repeated. Please close if this is not the correct logic after all.

### CODE REVIEW

**Comment by ArminTaheri** [comment]
helped by @natacha-beck

**Comment by prioux** [comment]
We have to be very carefule there, sometimes the change is subtle and it's not a repetition; but then I also agree it's entirely possible it is.

**Comment by ArminTaheri** [comment]
Agreed but it's the same exact code with the difference only being `.find(id)`

**Comment by prioux** [comment]
I'll make the modification in the R5 codebase instead. Thanks for reporting it. You'll be credited in the commit message.

**Pull request closed without merging**
