### PR TITLE
better user-facing pages for ToolConfigs resolves #1134

### LINKED ISSUE #1134: Make better user-facing pages for showing the information about ToolConfigs
Right now when launching tools or browsing the list of tool configs, a normal user has poor visibility into the 'description' field.

We should somehow show that description at launch time, and also maybe in a nice new 'show' page for normal users.

The ToolConfig index page has trouble showing the descriptions. See screenshot for the yellow box that appear on overlay right now:

Screen Shot 2021-06-15 at 15 56 28

### PR DESCRIPTION
**Pull request by MontrealSergiy**
show descriptions on users tool config pages

### CODE REVIEW

**Comment by natacha-beck** [comment]
I am not sure it is what @prioux wants. I test it and I think the `tool_configs` index table can get really long this way. Example of screenshot: 
Screen Shot 2021-11-02 at 1 44 24 PM

**Comment by MontrealSergiy** [comment]
@natacha-beck I think I can hide  half of columns that's are less interesting for average user

**Comment by MontrealSergiy** [comment]
@natacha-beck just pushed a commit to hide misc technical info, yet if user wish it can latter enable them

**Comment by MontrealSergiy** [comment]
of course if you have other ideas (crop descriptions to 4 lines may be, or put below the row) let me know

**Comment by prioux** [comment]
No, I don't think inserting the full description in the table is a solution. When the text is large (and it happens often) it doesn't work.

**Comment by prioux** [comment]
I'm not exactly sure what to do about this. I think we might want a new 'show' page for normal ToolConfigs, for normal users.

**Comment by prioux** [comment]
I'm closing this until I have a better idea on how to go about this. I'll put my comments in #1134

**Pull request closed without merging**
