### PR TITLE
ScratchDataProvider

### PR DESCRIPTION
**Pull request by prioux**
This is the implementation for #646 that will be the backbone of resolving the problem for #645 .

Please try out the utility helper method in the console and make sure all the behavior seems consistent.

### CODE REVIEW

**Comment by prioux** [comment]
Just a note. Annoyingly I started working on this on the branch I had created for another pull request, so the commits and files changed here include them both. Ignore the changes that are already described in the previous pull request please.

**Comment by prioux** [comment]
I'm going to rebase this.

**Comment by prioux** [comment]
The fact that this PR is failing the tests is because the codebase is missing some adjustments already made in the dev branch, so I wouldn't worry about that.

**Comment by shots47s** [comment]
This looks good and it is cool for me to see what you did to implement a new data provider, should we also add documentation of this DP to the wiki before committing?

**Pull request merged**
