### PR TITLE
[FIX] api_request when request came from jQuery

### PR DESCRIPTION
**Pull request by natacha-beck**

### CODE REVIEW

**Comment by natacha-beck** [comment]
Could fix the #1071

**Comment by MontrealSergiy** [comment]
it seems fix #1072 at the least for chrome yet not fully fixes #1071 (it allows one to chose his or all files by clicking 'select all' even though when you switch from all/my files or back the counter is not updated) 

image

**Comment by prioux** [comment]
@natacha-beck Is the CSV issue mentioned by @MontrealSergiy fixed ?

**Comment by natacha-beck** [comment]
I need to double check, I do not remember getting this issue when I tested
it.

**Comment by MontrealSergiy** [comment]
Actually is CSV is addressed by the PR, but not CBCSV (or probably any other operation).

**Comment by natacha-beck** [comment]
@MontrealSergiy I am looking at it.

**Comment by natacha-beck** [comment]
The CBCSV works too. From my point of view the only missing part is the update of the count, I am still on it.

**Comment by natacha-beck** [comment]
Let do a recap: 

For issue #1072, the bug is the following: 

> If the "select all files" link is pressed, and the user is in "see only my files" mode, the files selected will still be all the available files.
> See screenshot, which has all the numbers (a filter is applied on the DP, and there are 131530 files on that DP, though only 125 belong to the user):

So when the user is in "see only my files" mode, when the user clicks on 'select all files' it selected all the files available to the user (the one owned by the user + the one available to the user). **Normally it should not be the case with my PR**.

I feel like one of your test @MontrealSergiy  was to be in "Show all files" mode, then click on "select all", then switch to "Show only my file". In this case, I do not expect the selection of files to change (after all you just ask to change the view). For example, the persistent selection file is not updated every time you update a filter in the index page. 


For the following point: 

> Curiously, on the above snapshot, even though it says '5 files selected' link for csv generation will download list of 3 files but for other operations, such building cbrain-csv picks will contain all the files. 

Indeed but it was like that in CBRAIN or it should have been like that. The `Export to CSV` functionality was here before the `Create a CBCSV file` both functions have a different purpose:  

- **Export to CSV**: will create a list based on what is available on the index page. So if you have 3 files it will create a list with 3 entries.
- **Create a CBCSV file**: will create a list based on what is available in your persistent selection (that can differ from what you have in your index).

**Comment by MontrealSergiy** [comment]
ok then,

**Comment by prioux** [comment]
This PR seems to work fine in every cases I tried

**Comment by prioux** [comment]
Except: the 'export to csv' function now exports all pages, in the past it exported only the current page. Not sure if that's what we want.

**Comment by natacha-beck** [comment]
Indeed it is a modification I have done I can revert it if you want. Was
not sure about what we expected form the `Export to CSV`.

**Comment by prioux** [comment]
So the export to CSV behavior is caused by this, right?

https://github.com/aces/cbrain/pull/1073/files#diff-f57dc1e6518dd2853ec0f3c228ba9bbb8cc7aa9e57faaa74a226ff958cbc6fc4R132

In that case, if you revert that single line change, I will merge.

**Comment by prioux** [comment]
As a matter of clarification for @MontrealSergiy, the list of selected files persistently shoudl not really change if you change the mode: what is selected is what is selected, and that allows users to create a larger list by selecting things during multiple rounds of filtering the view and clicking 'select all'.

**Pull request merged**
