### PR TITLE
Added new SingBindmountDataProvider class

### PR DESCRIPTION
**Pull request by prioux**
This is a new DP class. To test this you need the following:

1. access to a computer, let's call it 'h' which can be local or remote
2. that computer must have Singularity 3.7 or better
3. in some new directory of your choice install:
  a) a file "sing_squashfs.simg" : a singualrity container file that contains at least "rsync"
  b) a ext3 or squashfs filesystem-in-a-file; this can be named whatever you want
  Note: I can provide you with examples for these two files.
4. configure the new DP in your CBRAIN, it will appear under the category 'Singularity Bind Mount'
  a) enter the remote host name 'h'
  b) enter a remote user, port, and make sure the SSH key of your CBRAIN is installed (just like a normal SSH DP)
  c) for the remote_dir attribute (shown as 'physical data localtion' in the form, enter the full path of the ext3 or squashfs file (yes, it's not a directory)
  d) for the 'Containerized Data Path' attribute, enter any path for something inside your filesystem-in-a-file, but prefixed with "/cbrain/" (even if there is no such directory in the filesystem). E.g. if you want to access stuff that is inside "/data/collection", you enter "/cbrain/data/collection" instead. If you want to access the root, enter just "/cbrain".

### CODE REVIEW

**Comment by prioux** [comment]
I have added two files in the CBRAIN service for helping you test the DP. You can find them in the project 'CBRAIN-Developers' (you are a member of that project).

* sing_squashfs.simg
* top-data-rw.ext3

This last file contains this simple data structure, listed with "." being "/" :

```
     2    4 drwxr-xr-x   6 root     root         4096 Mar 30 10:54 .
    19    8 -rwxrwxr-x   1 1000     1000         5404 Mar 29 17:12 ./withoverlay
    12    4 drwxrwxrwt   2 1000     1000         4096 Mar 30 10:56 ./rwdir
    20    0 -rw-r--r--   1 prioux   prioux          0 Mar 30 10:56 ./rwdir/abcd
    17    4 drwxrwxr-x   2 1000     1000         4096 Mar 29 17:12 ./top2
    18    4 -rw-rw-r--   1 1000     1000            6 Mar 29 17:12 ./top2/file.txt
    11   16 drwx------   2 root     root        16384 Mar 30 10:54 ./lost+found
    13    4 drwxrwxr-x   3 1000     1000         4096 Mar 29 17:12 ./top1
    15    4 drwxrwxr-x   2 1000     1000         4096 Mar 29 17:12 ./top1/subdir1
    16   36 -rwxr-xr-x   1 1000     1000        35064 Mar 29 17:12 ./top1/subdir1/cat
    14  136 -rwxr-xr-x   1 1000     1000       133792 Mar 29 17:12 ./top1/ls
```

(uids and gids will be different depending on where you open it up).

You can inspect the ext3 with this command:

```
singularity shell -B top-data-rw.ext3:/cbrain:image-src=/,ro sing_squashfs.simg
```

will will mount the / of the ext3 under /cbrain, like the DP does.

**Comment by MontrealSergiy** [comment]
In the view mode I do not see containerized path, only full path to singularity file

**Comment by MontrealSergiy** [comment]
[cbrain_SingbindDP.pdf](https://github.com/aces/cbrain/files/6273606/cbrain_SingbindDP.pdf)

**Comment by prioux** [comment]
Please don't post PDFs here, just add screenshots

**Comment by prioux** [comment]
You are right, it's a bug in the view code. In the meantime if you need to change that value, use the console.

**Comment by MontrealSergiy** [comment]
Screenshot is below image

**Comment by prioux** [comment]
Added a commit with the fix

**Comment by MontrealSergiy** [comment]
now container "path" is shown

**Comment by MontrealSergiy** [comment]
I was not able to browse the data provider - no files are shown. I though used a VM (vagrant box) rather than real remote pc.

**Comment by prioux** [comment]
Well, what do you get when you type

```ruby
fis=@d.provider_list_all;1
```

in the console? fis should be an array of FileInfo objects. If you get an exception, it might tell you something about an error in the configuration.

**Comment by MontrealSergiy** [comment]
I tried today a slightly different vm's setup (with a 'private' network, on my home pc) and the feature worked well. Maybe I will try latter again it tell if I see any problems. I understand it is readonly.

For old setup I got no error message, but when tried a ssh dp to same machines , it generated an exception, so, most likely the problem with key or other setup details, not the feature under test. Ideally,  some detailed warnings about connection or auth issues are desirable, but I guess an admin will figure anyway if something not working. 
image

**Comment by prioux** [comment]
OK, good, thank you @MontrealSergiy . If you could just approve the PR now ?

**Comment by MontrealSergiy** [comment]
the feature works, approved

**Review by MontrealSergiy — APPROVED** [review]
feature works

**Comment by MontrealSergiy** [comment]
Some explanations how to configure could be added to Data Provider Type Information

**Pull request merged**
