### PR TITLE
Admins can now provide dashboard messages

### PR DESCRIPTION
**Pull request by prioux**
This implements #1043

### CODE REVIEW

**Comment by prioux** [comment]
To test: on CBRAIN side, as admin, go to Messages, click 'Leave Message' then two new buttons will appear at the top.

**Comment by MontrealSergiy** [comment]
you do not want to keep the group dropdown? May be useful if you want to target different groups, like UK Biobank or admins

**Comment by MontrealSergiy** [comment]
CBRAIN dashboard might look ugly, especially for narrow and wide messages. Should align and flow better 
image
image

**Comment by MontrealSergiy** [comment]
wide message : credits should not show here, I think
image
image

Whole whiteboard disappears for wide (long) message
image

**Comment by prioux** [comment]
Right, so there are some weird rendering problems. I'll look into this

**Comment by prioux** [comment]
I think the first screenshot is because you made a mistake. Your HTML was invalid in your message. We can see that everything isn the page is in italics. Please make sure you enter valid HTML

**Comment by MontrealSergiy** [comment]
besides italic on the first screenshot the panel alignment is not ideal.
It would be great to address isolating html errors to the message itself, not sure may be iframe or other container. One can expect admin know html, but occasional typo or accidental enter push are possible.

**Pull request merged**
