### PR TITLE
Fixed QC panel bug

### PR DESCRIPTION
**Pull request by natacha-beck**
Fixed for #900

### CODE REVIEW

**Comment by prioux** [comment]
I thought we had agreed this PR would include a copy of the patch made in master to fix the javascript code?

**Comment by prioux** [comment]
I'm talking about this: https://github.com/aces/cbrain/commit/b933ae8ed8b39cf11f68693aca318b62e35f5682

**Comment by prioux** [comment]
I am not able to reproduce the original bug... :-( Please see me so we can have a look.

**Comment by natacha-beck** [comment]
> I thought we had agreed this PR would include a copy of the patch made in master to fix the javascript code?

Done.

**Pull request merged**
