### PR TITLE
Remove time_of_death attribute from Data Provider 

### PR DESCRIPTION
**Pull request by MontrealSergiy**
see #1373

### CODE REVIEW

**Comment by prioux** [comment]
You schema update changes the collation character set for the tables, please don't do that. Ensure that your DB is using the proper collation keywords before you run your migration so that it doesnt' change (You'll probably have to update  manually your tables with a `alter table` command in your SQL client)

**Review by prioux — CHANGES_REQUESTED** [review]
Collation are changed and they shouldn't.

**Comment by MontrealSergiy** [comment]
the collation is corrected

**Comment by prioux** [comment]
This PR is fine.

**Pull request merged**
