### PR TITLE
Added support for a 'cbrain:inherit-from-class' private attribute in Boutiques' JSON schema.

### PR DESCRIPTION
**Pull request by glatard**
This modification allows for some customization of tasks created with Boutiques. Feedback from @remibernard would be appreciated if he has time.

### CODE REVIEW

**Comment by remibernard** [comment]
While I can somewhat see the appeal of switching the base class when generating task classes for manual edition, isn't this exactly one of the reasons the generator was made the way it is now?

If the goal is to customize automatically generated tasks, then modifying the base class seems like an odd choice; maybe a way to reopen the class would be a cleaner design?

**Comment by glatard** [comment]
I have n tasks that need to share the same method, which clearly requires inheritance. I could generate the n classes and edit them manually to make them derive from the right class, but that sounds like an overkill while adding this attribute is so simple. In general, and as you noticed initially, it is much more maintainable to rely only on the JSON descriptor than to generate the classes.

**Comment by remibernard** [comment]
Using an utility class/module is not possible?

**Comment by glatard** [comment]
It wouldn't be easy... Besides, all these tasks are different pipelines from the same framework, so it makes sense that they have a super class in common.

**Pull request merged**
