### PR TITLE
New Token page for NH users.

### PR DESCRIPTION
**Pull request by prioux**
Also includes a few other fixes:

* We log the user agent for the first API request
* Session cookies are sent with SameSite: Strict
* The switcher button is less likely to switch to bad routes on the other side

### CODE REVIEW

**Comment by prioux** [comment]
Will fix #999

**Comment by prioux** [comment]
@MontrealSergiy You're right and I removed it. It's not a the Rails level that we can handle this sort of problem anyway. We'll get a contract with cloudflare if we're ever big. But that's not likely.

**Comment by MontrealSergiy** [comment]
webpage works. I think it is not so difficult to limit users clicks properly by checking timestamps but not big deal to me

**Comment by MontrealSergiy** [comment]
image

**Pull request merged**
