### PR TITLE
Disk Quota System

### PR DESCRIPTION
**Pull request by prioux**
To start testing this, go to the data provider index page and you'll see a new button 'Disk Quotas'.

Note that although the interface shows the bytes limits in pretty sizes (e.g. 3.2 GB or 6.1 MB etc) the values you must enter in a quota is in `bytes`!

### CODE REVIEW

**Comment by prioux** [comment]
Other notes:

This system has no support for quotas based on projects. From what I observed, it's fine this way.

**Comment by prioux** [comment]
Hi @MontrealSergiy, yes you're right this is pretty strict, but this is a`hard quota` system. What you are referring to is a 'soft quota` system, and I think we should implement that separately, maybe with a `rake` task that we run from time to time. I will think about it and create an issue or pull request for the `soft quota` system. I can imagine a rake task scanning all user quotas and creating an internal message when a user is using more than 80% of their quota.

**Comment by prioux** [comment]
I added a 'quotas' tab in the admin interface, and for normal users a 'quotas' menu entry in the 'resources' menu at the very top.

**Comment by prioux** [comment]
Also, I've added coloring code that will turn the top bar 'green' when the currently checked out git branch is not one of the normal ones. I think it's useful for us, developers.

**Comment by MontrealSergiy** [comment]
is limit on ":userfiles" registered files or file collections, or total number of files?

**Comment by prioux** [comment]
Total number of files. As you can see at line 81 of the DiskQuota model.

**Comment by MontrealSergiy** [comment]
in new quota form, if admin forgot to enter dp name (or is it id), the admin is redirected to quota index, which is different from how most form implemented in cbrain (stay on new page and hightlight erroneous field).

**Comment by prioux** [comment]
OK, that seems a bug, I'll fix it.

**Comment by prioux** [comment]
Ths fix was easy and you get nice little red boxes around the missing attributes.

**Comment by MontrealSergiy** [comment]
The default quota on number of files does not seem work. Will try give an individual quota

**Comment by MontrealSergiy** [comment]
I tried to set individual and default quota on file number neither did work: I was able to upload more files than allowed by quota

**Comment by prioux** [comment]
Okay, I can have a look, but note that this quota system triggers only once the quota is already broken, not before. It will allow a process to create a file or directory tree when the quota is OK, even if by doing so the limit gets to be exceeded. Further files will then be prevented from being created.

**Comment by MontrealSergiy** [comment]
For 'default' quota of 2 files I was able to upload 5 files and counting

**Comment by prioux** [comment]
@MontrealSergiy There's something else I forgot to mention. The system caches the usage information for a pair [user, data_provider] for about one minute.

**Comment by MontrealSergiy** [comment]
I waited 1 min with a timer still can upload

**Comment by prioux** [comment]
Can you show me a screenshot of the quotas index table (as seen by the admin) and tell me on which DP you were uploading?

**Comment by MontrealSergiy** [comment]
image

**Comment by MontrealSergiy** [comment]
image

**Comment by prioux** [comment]
Oh never mind, I was looking at the wrong thing

**Comment by MontrealSergiy** [comment]
once again, I am testing 'default quota' for all users, so that's should not matter is it serge or sboroday users

**Comment by prioux** [comment]
@MontrealSergiy Thanks for finding this bug. I pushed a new commit, just pull it and let me know.

**Comment by MontrealSergiy** [comment]
I find it a bit strange to see dropdowns on the new quota page, but since your are the main user for it, I am sure you will not be confused, so up to you

**Review by MontrealSergiy — APPROVED** [review]
seems ok

**Pull request merged**
