### PR TITLE
Bourreau application_controller.rb missing new line at end of file

### PR DESCRIPTION
**Pull request by Jkat**
I just noticed there was no new line at the end of this file. I did not really check other files but this should help with legibility.

### CODE REVIEW

**Comment by prioux** [comment]
Seriously? You create a branch and a commit for a single missing newline ?!?

You could have waited until you have a more significant mod to make, and include that change in it...

**Comment by prioux** [comment]
Besides, the last line ("end") did have a newline, so what you did was not add a missing newline, you added a blank line.

**Comment by Jkat** [comment]
Unfortunately Ruby is one of the few languages I have never touched so my contributions would likely be very limited.

**Comment by Jkat** [comment]
Thanks for pointing out my careless mistake too!

**Comment by prioux** [comment]
No prob. Well, once you do have proper changes to suggest, we'll merge them. I closed you other pull request too.

**Pull request closed without merging**
